# Generated by Django 2.2.9 on 2020-08-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persos',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
