# Generated by Django 2.2.9 on 2020-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20200818_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persos',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
